name: ci-golang
on: 
  pull_request:
    branches:
      - develop
strategy:
  matrix:
    go: ['1.5','1.4']   
jobs:
  check-app:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with: 
          go-version: ${{ matrix.go }}
      - run: go test
      - run: go run math.go